language: scala
scala: 2.11.11
sudo: required
dist: trusty

services:
  - docker
  - redis

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - mkdir containers
  - git clone https://github.com/wurstmeister/kafka-docker.git containers/kafka
  - "sed -i 's/KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100/KAFKA_ADVERTISED_HOST_NAME: localhost/' containers/kafka/docker-compose-single-broker.yml"
  - "echo 'EXPOSE 9092' >> containers/kafka/Dockerfile"
  - cat containers/kafka/docker-compose-single-broker.yml
  - cat containers/kafka/Dockerfile
  - docker-compose -f "containers/kafka/docker-compose-single-broker.yml" up -d
  - docker ps -a

matrix:
  include:
    - env: SCALA_VERSION=2.11.11
      os: linux
      jdk: oraclejdk8

before_script:
  - sleep 10

script:
  - sbt package
  - sbt 'set parallelExecution in ThisBuild := false' clean coverage test

after_success:
  - sbt coverageReport coveralls

notifications:
  email: false
