version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - overlay
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # redis:
  #   image: redis
  #   expose: 6379

  elk:
    image: sebp/elk:512
    restart: always
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
    expose:
      - 9300
    networks:
      - overlay
    volumes:
      - elk:/var/lib/elasticsearch
    environment:
      ES_MIN_MEM: 5g
      ES_MAX_MEM: 5g

  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    expose:
      - 2181
    networks:
      - overlay
    volumes:
      - zk:/data

  kafka:
    image: wurstmeister/kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - overlay
    volumes:
      - kafka:/kafka

  jobmanager:
    image: flink:1.4.2-scala_2.11-alpine
    expose:
      - 6123
    ports:
      - 8082:8081
    restart: always
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - overlay
    links:
      - zookeeper:zookeeper
      - kafka:kafka

  taskrunner:
    image: flink:1.4.2-scala_2.11-alpine
    expose:
      - 6121
      - 6122
    depends_on:
      - jobmanager
    restart: always
    command: taskmanager
    links:
      - jobmanager:jobmanager
      - zookeeper:zookeeper
      - kafka:kafka
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - overlay

volumes:
  elk:
  mongodb:
  kafka:
  zk:

networks:
  overlay:
