version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - overlay
    volumes:
      - mongodb:/data/db

  # redis:
  #   image: redis

  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    expose:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    networks:
      - overlay

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 206.189.108.210
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - overlay

  jobmanager:
    image: flink:1.4.2-scala_2.11-alpine
    expose:
      - 6123
    ports:
      - 8082:8081
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - overlay

  taskrunner:
    image: flink:1.4.2-scala_2.11-alpine
    expose:
      - 6121
      - 6122
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - overlay

volumes:
  mongodb:

networks:
  overlay:
